### PR TITLE
Updated to support Interstellar Wars Era

### PR DESCRIPTION
**Pull request by TedTschopp**
I have tested this on a Windows Machine VM and works fine.   Looking forward to seeing this go live so we can use it in a campaign.

### CODE REVIEW

**Comment by Grauenwolf** [comment]
Gonna need this in the Blazor/TravellerTools 2 branch as well. Hopefully it can be pulled across directly.

**Comment by TedTschopp** [comment]
I also have a PR to add era to the map that the trade info puts up for each system within jump distance. But I didn’t submit it yet as I am looking for any other dependancies for era in the code. 
 

📲Ted Tschopp

**Comment by Grauenwolf** [comment]
Pushing TravellerTool 2 branch with matching changes.

**Comment by Grauenwolf** [comment]
TravellerTools 2 has been updated. https://travellertoolsdemo.azurewebsites.net/world/IW/0,3/1222/info

**Comment by Grauenwolf** [comment]
Deployed to http://travellertools.azurewebsites.net/Home/TradeInfo?sectorX=0&sectorY=3&hexX=24&hexY=20&maxJumpDistance=1&brokerScore=0&advancedMode=false&illegalGoods=false&edition=2016&advancedCharacters=false&streetwiseScore=0&raffle=false&milieu=IW

@TedTschopp Thank you for your help.

**Comment by Grauenwolf** [comment]
> I also have a PR to add era to the map that the trade info puts up for each system within jump distance. But I didn’t submit it yet as I am looking for any other dependancies for era in the code. 📲Ted Tschopp

I think the only thing I do with that code is pass it directly to TravellerMap. 

These days I'm not personally adding new features to TravellerTools/main. On the rare occasions I have time to work on it, my updates are going into the Blazor version. But if you want to submit anything, to either, I'll gladly accept them.

**Pull request merged**
